Feat:Sidebar
dlab-team/c18-frontend pull request #12
Opened 2024-04-27 21:03 UTC by iredelmar

2024-05-03 12:53 UTC, ejbogantes requested changes
Revisar conflictos y por qué se borró el .gitignore?

2024-05-15 03:50 UTC, hlcxpl submitted a review, later dismissed
arreglado
@ejbogantes

2024-05-15 04:23 UTC, hlcxpl approved these changes, later dismissed

2024-05-15 04:30 UTC, hlcxpl approved these changes

2024-05-15 04:30 UTC, hlcxpl commented
> arreglado
@ejbogantes

2024-05-15 04:31 UTC, hlcxpl commented
> arreglado

 @ejbogantes

2024-05-15 12:14 UTC, hlcxpl approved these changes, later dismissed

2024-05-15 16:16 UTC, ejbogantes approved these changes

2024-05-16 21:06 UTC, ejbogantes requested changes
Resolver los conflictos

2024-05-16 23:32 UTC, iredelmar reviewed
Resuelto

2024-05-16 23:51 UTC, hlcxpl approved these changes, later dismissed

2024-05-16 23:54 UTC, hlcxpl submitted a review, later dismissed

2024-05-16 23:58 UTC, ejbogantes approved these changes, later dismissed

2024-05-17 00:44 UTC, hlcxpl approved these changes

2024-05-17 00:53 UTC, ejbogantes approved these changes

2024-05-17 02:32 UTC, merged