75 feat/iloaiza
dlab-team/c18-frontend pull request #15
Opened 2024-04-29 02:08 UTC by iredelmar

Se agrega componente Vista de Metas y Objetivos

2024-04-29 02:18 UTC, ejbogantes approved these changes

2024-05-03 12:53 UTC, ejbogantes requested changes
Revisar los conflictos, y por qué se borró el .gitignore?

2024-05-07 22:36 UTC, ejbogantes approved these changes

2024-05-15 16:15 UTC, ejbogantes requested changes
Revisar conflictos

2024-05-16 23:58 UTC, ejbogantes approved these changes

2024-05-16 23:58 UTC, ejbogantes approved these changes, later dismissed

2024-05-17 00:50 UTC, hlcxpl approved these changes

2024-05-17 02:21 UTC, ejbogantes approved these changes

2024-05-17 02:22 UTC, ejbogantes approved these changes

2024-05-17 02:44 UTC, ejbogantes approved these changes

2024-05-17 14:24 UTC, merged