77 feat/lsanchez
dlab-team/c18-frontend pull request #16
Opened 2024-05-06 21:45 UTC by hlcxpl

2024-05-07 16:08 UTC, ejbogantes requested changes
Hay algunos conflictos por resolver.

2024-05-15 03:21 UTC, hlcxpl reviewed
fixed

2024-05-15 03:27 UTC, hlcxpl reviewed
arreglado

2024-05-15 03:28 UTC, hlcxpl commented
> fixed
@ejbogantes

2024-05-15 03:28 UTC, hlcxpl commented
> arreglado

@ejbogantes

2024-05-15 03:54 UTC, hlcxpl reviewed
.

2024-05-15 04:04 UTC, hlcxpl reviewed
.

2024-05-15 04:15 UTC, hlcxpl reviewed
arre

2024-05-15 16:15 UTC, ejbogantes approved these changes

2024-05-15 23:45 UTC, merged